from .state import CodeScorerSchema, CodeInspectorSchema, CodeProfılerSchema
from typing import Optional

INSPECTOR_REPORT = """
ERRORS REPORT;
{errors}

SUGGESTİONS REPORT;
{suggestions}
"""

PROFILER_REPORT = """
Summary Of The Code;
{summary}

Lint Warnings Of The Code;
{lint_warnings}

Strengths Of The Code;
{pros}

Weaknesess Of The Code;
{cons}
"""

ERROR_FORMAT = """
Error Title: {title}
Error Type: {error_type}
Error Severity: {error_severity}
Error Line Range: {line_range}
Error Reason: {error_reason}
Fix Suggestion: {fix_suggestion}
Fixed Code: {fixed_code}
Original Code: {original_code}
Fix Effort: {fix_effort}
"""

SUGGESTION_FORMAT = """
Suggestion Title: {title}
Suggestion Line Range: {line_range}
Suggestion Reason: {suggestion_reason}
Suggested Code: {suggested_code}
Original Code: {original_code}
Suggestion Priority: {suggestion_priority}
Suggestion Effort: {suggestion_effort}
"""

SCORER_REPORT = """
SCORES REPORT;

Security Score: {security_score}
Cleanliness Score: {cleanliness_score}
Performance Score: {performance_score}
Overall Score: {overall_score}
Scalibilty Score: {scalibility_score}
Breaking Changes Score: {breaking_changes_score}

Score Reasons;
{scores_reasons}
"""


def prepare_code_for_llm(raw_code: str) -> str:
    """
    
    Number the lines of code for the workers.
    
    """
    lines = raw_code.splitlines()
    numbered_lines = [f"{i+1} | {line}" for i, line in enumerate(lines)]
    return "\n".join(numbered_lines)


def report_formatter(
    code: Optional[str] = None,
    scorer_report: Optional[CodeScorerSchema] = None,
    profiler_report: Optional[CodeProfılerSchema] = None,
    inspector_report: Optional[CodeInspectorSchema] = None
) -> str:
    
    """
    Aggregates worker outputs into a unified, LLM-optimized and human friendly report.

    Args:
        code (Optional[str]):
            The source code subject to analysis.
        scorer_report (Optional[CodeScorerSchema]):
            The report object generated by the scorer worker in the analyzer graph.
        profiler_report (Optional[CodeProfılerSchema]):
            The report object generated by the profiler worker in the analyzer graph.
        inspector_report (Optional[CodeInspectorSchema]):
            The report object generated by the inspector worker in the analyzer graph.

    Returns:
        str: A formatted, structured report string optimized for LLM context 
            and human readability.
    """
    
    formatted_reports = []
    
    if code and isinstance(code, str):
        numbered_code = prepare_code_for_llm(code)
        formatted_reports.append(f"Code;\n\n{numbered_code}")

    if profiler_report and isinstance(profiler_report, CodeProfılerSchema):
        lint_warnings = "\n".join(profiler_report.lint_warnings)
        pros = "\n".join(profiler_report.pros)
        cons = "\n".join(profiler_report.cons)
        summary = profiler_report.summary

        profiler_format = PROFILER_REPORT.format(summary = summary, lint_warnings = lint_warnings, pros = pros, cons = cons)

        if profiler_format:
            formatted_reports.append(profiler_format)

    if inspector_report and isinstance(inspector_report, CodeInspectorSchema):
        errors = []
        suggestions = []

        for e in inspector_report.errors:
            formatted_error = ERROR_FORMAT.format(
                title = e.title,
                error_type = e.error_type,
                error_severity = e.error_severity,
                line_range = e.line_range,
                error_reason = e.error_reason,
                fix_suggestion = e.fix_suggestion,
                fixed_code = e.fixed_code,
                original_code = e.original_code,
                fix_effort = e.fix_effort,
            )
            if formatted_error:
                errors.append(formatted_error)

        for s in inspector_report.suggestions:
            formatted_suggestion = SUGGESTION_FORMAT.format(
                title = s.title,
                line_range = s.line_range,
                suggestion_reason = s.suggestion_reason,
                suggested_code = s.suggested_code,
                original_code = s.original_code,
                suggestion_priority = s.suggestion_priority,
                suggestion_effort = s.suggestion_effort
            )
            if formatted_suggestion:
                suggestions.append(formatted_suggestion)

        joined_errors = "\n".join(errors) if errors else ""
        joined_suggestions = "\n".join(suggestions) if suggestions else ""

        if joined_errors and joined_suggestions:
            inspector_format = INSPECTOR_REPORT.format(errors = joined_errors, suggestions = joined_suggestions)
            formatted_reports.append(inspector_format)

    if scorer_report and isinstance(scorer_report, CodeScorerSchema):
        scorer_format = SCORER_REPORT.format(
            security_score = scorer_report.security_score,
            cleanliness_score = scorer_report.cleanliness_score,
            performance_score = scorer_report.performance_score,
            overall_score = scorer_report.overall_score,
            scalibility_score = scorer_report.scalibility_score,
            breaking_changes_score = scorer_report.breaking_changes_score,
            scores_reasons = scorer_report.scores_reasons
        )

        if scorer_format:
            formatted_reports.append(scorer_format)

    return "\n".join(formatted_reports)